services:
  - type: web
    name: mock-simulator
    env: docker
    region: oregon
    plan: free
    dockerCommand: "uvicorn mocksim.server:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SIMULATOR_START_MODE
        value: paused
      - key: PORT
        value: 8000

  - type: web
    name: fuelops-dashboard
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: SIM_BASE_URL
        value: https://mock-simulator.onrender.com
      - key: ENABLE_ADMIN_PROXY
        value: "true"
      - key: PORT
        value: 8080
